import {
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiHtml5,
  SiCss3,
  SiMongodb,
} from 'react-icons/si'
import { FaSass } from 'react-icons/fa'
import { DiGit } from 'react-icons/di'

export const links = [
  {
    title: 'Javascript',
    icon: <SiJavascript />,
    url: 'https://www.javascript.com/',
    key: 'jVw1awtdhV',
    darkfg: '#ffea00',
    lightfg: '#ffa200',
  },
  {
    title: 'React.JS',
    icon: <SiReact />,
    url: 'https://reactjs.org/',
    key: 'ZbwW9jszKR',
    darkfg: '#90e0ef',
    lightfg: '#00b4d8',
  },
  {
    title: 'Next.JS',
    icon: <SiNextdotjs />,
    url: 'https://nextjs.org/',
    key: 'UwAWtcp3FD',
    darkfg: '',
    lightfg: '',
  },
  {
    title: 'Node.JS',
    icon: <SiNodedotjs />,
    url: 'https://nodejs.org/en/',
    key: '2L7yAiOwqv',
    darkfg: '#70e000',
    lightfg: '#38b000',
  },
  {
    title: 'Express.JS',
    icon: <SiExpress />,
    url: 'https://expressjs.com/',
    key: '0U1Zg67Wwu',
    darkfg: '#ffd6ff',
    lightfg: '',
  },
  {
    title: 'HTML5',
    icon: <SiHtml5 />,
    url: 'https://developer.mozilla.org/en-US/docs/Glossary/HTML5',
    key: '7ztkCqAL9t',
    darkfg: '#e01e37',
    lightfg: '#da1e37',
  },
  {
    title: 'CSS3',
    icon: <SiCss3 />,
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
    key: 'idncGpTLlb',
    darkfg: '#4d84fc',
    lightfg: '#185ef7',
  },
  {
    title: 'Sass',
    icon: <FaSass />,
    url: 'https://sass-lang.com/',
    key: 'Iz3dpc7C9J',
    darkfg: '#ff85a1',
    lightfg: '#ff0a54',
  },
  {
    title: 'Git',
    icon: <DiGit />,
    url: 'https://git-scm.com/',
    key: '9BVwD0IZrc',
    darkfg: '#f05030',
    lightfg: '#f05030',
  },
  {
    title: 'MongoDB',
    icon: <SiMongodb />,
    url: 'https://www.mongodb.com/',
    key: '6qqzsZf2zZ',
    darkfg: '#80ffdb',
    lightfg: '#0cd17f',
  },
]
